<a href="https://colab.research.google.com/github/majorquev/DBDC_202309_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/C2/Clase_2_01_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com



### 3.2 Matrices

En R, así como en otros lenguajes de programación, una matriz es básicamente un arreglo bi-dimensional, donde las entradas horizontales se entienden como filas y las verticales como columnas. Es posible imaginar una matriz como un arreglo de vectores como columnas (o filas) del mismo largo.

 * ¿Qué se guarda en una matriz?<br>
    Sólo datos de un mismo tipo.
     
 * ¿Cómo se declara una matriz?<br>
    Se puede definir de varias maneras, indicando los elementos que la componen, o combinando vectores como filas o columnas.

 * ¿Cómo se accede a sus elementos?<br>
    Indicando la posición del vector fila, seguido de la posición del vector columna (como es usual).

In [2]:
# 3.2 Matrices ------------
#?matrix de dos filas y 3 columnas, parametros ncol, nrow y byrow
# recibe un vector de elementos
A <- matrix(c(1,1,2,3,5,8), ncol = 3, nrow = 2)
A

B <- matrix(c(1,1,2,3,5,8), ncol = 3, nrow = 2, byrow = T)
B


[,1] [,2] [,3]
[1,] 1    2    5   
[2,] 1    3    8

[,1] [,2] [,3]
[1,] 1    1    2   
[2,] 3    5    8

In [4]:
# clase y atributo dim
dim(A)
class(A)

[1] 2 3

[1] "matrix" "array"

In [5]:
# Genere dos vectores del mismo largo y forme una matriz.
f1 <- c(1,1,2)
f2 <- c(3,5,8)




In [10]:
# funciones cbind() [une vectores como columnas]
# y rbind() [une vectores como filas] (pensadas para matrices)
#?cbind
# Generar una matriz de 2x3
M <- rbind(f1,f2)
M

# Generar una matriz de 3x2
M2 <- cbind(f1,f2)
M2

[,1] [,2] [,3]
f1 1    1    2   
f2 3    5    8

f1 f2
[1,] 1  3 
[2,] 1  5 
[3,] 2  8

In [11]:
# NOTA: Podemos añadir una fila/columna a una matriz existente
rbind(M,c(8,8,8))

cbind(M2,c(8,8,8))

[,1] [,2] [,3]
f1 1    1    2   
f2 3    5    8   
   8    8    8

f1 f2  
[1,] 1  3  8
[2,] 1  5  8
[3,] 2  8  8

In [12]:
# NOTA: Si definimos una matriz con un vector de largo incorrecto

matrix(c(1,1,2,3,5), ncol = 3, nrow = 2)

Warning message in matrix(c(1, 1, 2, 3, 5), ncol = 3, nrow = 2):
“data length [5] is not a sub-multiple or multiple of the number of rows [2]”


[,1] [,2] [,3]
[1,] 1    2    5   
[2,] 1    3    1

In [13]:
# si combinamos vectores de distinto largo?
# R recicla valores (recordar explicación)
rbind(c(1,2,3), c(10,20))



Warning message in rbind(c(1, 2, 3), c(10, 20)):
“number of columns of result is not a multiple of vector length (arg 2)”


[,1] [,2] [,3]
[1,]  1    2    3  
[2,] 10   20   10

In [14]:
# función diag para la definición de matrices diagonales
#?diag


diag(1:5)


[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    2    0    0    0   
[3,] 0    0    3    0    0   
[4,] 0    0    0    4    0   
[5,] 0    0    0    0    5

In [15]:
M

[,1] [,2] [,3]
f1 1    1    2   
f2 3    5    8

In [16]:
# Podemos acceder a los elementos de una matriz
# indicando la posición de la fila y la columna de la casilla correspondiente.
# Ejemplo (rescatar el 5 de posiciòn 2,2 de la matriz M):
M[2,2]


f2 
 5

In [17]:
# quiero rescatar el elemento "(2,1)"

M[2,1]

f2 
 3

In [19]:

# CUIDADO:No es lo mismo que
M[c(2,5)] # R entiende que la matriz es el vector leído por columnas.

[1] 3 2

In [21]:
# Para acceder a una fila completa
M[1,]

# Para acceder a una columna completa
M[,3]


[1] 1 1 2

f1 f2 
 2  8

In [22]:
M

[,1] [,2] [,3]
f1 1    1    2   
f2 3    5    8

In [24]:
#Recordemos que podemos actualizar elementos de un vector como:

# quiero cambiar el 5 por un -99 (el 5 de la pos 2,2)
M[2,2] <- -99


In [25]:
M

[,1] [,2] [,3]
f1 1      1  2   
f2 3    -99  8

In [28]:
# NOTA: Nombres de filas y columnas
rownames(M)
colnames(M)

[1] "f1" "f2"

NULL

In [29]:
colnames(M) <- c("c1","c2","c3")

In [30]:
M

c1 c2  c3
f1 1    1 2 
f2 3  -99 8

In [ ]:
# Acceso mediante nombres


In [31]:
# Acceso mediante nomnbres
# Elemento de la segunda fila tercera columna (2,3)

M["f2","c3"]

[1] 8

In [32]:
# Acceso mediante "indicatrices" lógicas
#Quiero obtener los elementos (1,1) y (2,3) de M3
# 1: Crear una matriz de 2x3 con TRUE en dichas posiciones y FALSE en las restantes.

ind <- matrix(c(T,F,F,F,F,T), ncol = 3, nrow = 2)

In [33]:
ind

[,1]  [,2]  [,3] 
[1,]  TRUE FALSE FALSE
[2,] FALSE FALSE  TRUE

In [34]:
# Podemos evaluar las casillas de una atriz mediante sentencias lógicas
M[ind]

[1] 1 8

In [36]:
M[M >= 3]

[1] 3 8

**Álgebra de matrices**

Las operaciones suma (resta) y ponderación por escalar se llevan cabo mediante los mismos operadores utilizados para valores numéricos y vectores (+,-,*, /). Para multiplicar matrices en cambio, se utiliza el operador %*%, mientras que para invertirlas se utiliza la función solve(), t() para transponer y det() para el cálculo del determinante en el caso de matrices cuadradas.

In [ ]:
# transponer una matriz
# t()

In [ ]:
# 3.2 Álgbra de matrices  ------------
# Ejemplo simple de álgebra de matrices



In [ ]:
# Multiplicación de matrices
M2 * M1 # multiplicación componente a componente
# %*%

In [ ]:
# podemos calcular determinantes
# ?det



In [ ]:
# Podemos invertir matrices
# ?solve()
