<a href="https://colab.research.google.com/github/majorquev/DBDC_202309_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/C2/Clase_2_02_listas_y_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com


## 5. Listas y Dataframes

### 5.1 Listas

Hasta aquí contamos con dos tipos de objetos para almacenar datos; vectores y matrices. Sin embargo, en ambos casos se tiene la limitante de que no es posible combinar distintos tipos de datos en diferentes entradas. Un objeto que permite una mayor flexibilidad son las listas. En R, una lista es básicamente un arreglo unidimensional, donde en cada entrada es posible almacenar distintos **objetos** (los cuales a su vez pueden almacenar distintos tipos de datos (u otros objetos).
En resumen,

   * ¿Qué son?<br>
    Arreglos unidimensionales que guardan distintos tipos de datos u objetos.<br>

   * ¿Cómo se declaran?<br>
    Se pueden declarar mediante el comando list() o combinando listas existentes. <br>
    
   * ¿Cómo se accede a sus elementos?<br>
    Usando [ ] (retorna lista), o bien usando [ [ ] ] (retorna el objeto).
    En cada caso se puede indicar la posición o nombre del objeto que se quiere rescatar.<br>
    Otra manera es mediante el símbolo $ seguido del nombre del objeto.



In [1]:
# 5. Listas y dataframes ------------
# 5.1 Listas  ------------
# Cómo declarar una lista (comando list() )
#num,letra, pl, mat, lista
# Podemos guardar los objetos en slots con nombres
l1 <- list(num = c(1,3,5),
           letra = LETTERS,
           pl = "Hoy es lunes",
           mat = matrix(c(1,3,5,7), nrow = 2, ncol = 2),
           lista = list(x = c("a","b"),
                        lgl = c(T,F,F)))

In [2]:
# estructura
str(l1)

List of 5
 $ num  : num [1:3] 1 3 5
 $ letra: chr [1:26] "A" "B" "C" "D" ...
 $ pl   : chr "Hoy es lunes"
 $ mat  : num [1:2, 1:2] 1 3 5 7
 $ lista:List of 2
  ..$ x  : chr [1:2] "a" "b"
  ..$ lgl: logi [1:3] TRUE FALSE FALSE


In [3]:

l2 <- list(1:5, "x", c(T,F))

In [5]:
str(l2)

List of 3
 $ : int [1:5] 1 2 3 4 5
 $ : chr "x"
 $ : logi [1:2] TRUE FALSE


In [4]:
l2

[[1]]
[1] 1 2 3 4 5

[[2]]
[1] "x"

[[3]]
[1]  TRUE FALSE

In [6]:
l1

$num
[1] 1 3 5

$letra
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

$pl
[1] "Hoy es lunes"

$mat
     [,1] [,2]
[1,]    1    5
[2,]    3    7

$lista
$lista$x
[1] "a" "b"

$lista$lgl
[1]  TRUE FALSE FALSE

In [7]:
# Podemos combinar listas
l3 <- c(l1,l2)
str(l3)

List of 8
 $ num  : num [1:3] 1 3 5
 $ letra: chr [1:26] "A" "B" "C" "D" ...
 $ pl   : chr "Hoy es lunes"
 $ mat  : num [1:2, 1:2] 1 3 5 7
 $ lista:List of 2
  ..$ x  : chr [1:2] "a" "b"
  ..$ lgl: logi [1:3] TRUE FALSE FALSE
 $      : int [1:5] 1 2 3 4 5
 $      : chr "x"
 $      : logi [1:2] TRUE FALSE


In [8]:
# Acceso mediante posición
l1[2] # es una lista

$letra
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [9]:
l1[c(2,4)] # esto es una lista

$letra
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

$mat
     [,1] [,2]
[1,]    1    5
[2,]    3    7

In [12]:
class(l1[2])
class(l1[c(2,4)] )

[1] "list"

[1] "list"

In [16]:
# NOTA lista[.] retorna un lista con un elemento,
# lista[[.]] retorna el elmento de la lista lista[.]
l1[4] # Una lista con la matriz
l1[[4]] # Matriz


$mat
     [,1] [,2]
[1,]    1    5
[2,]    3    7

[,1] [,2]
[1,] 1    5   
[2,] 3    7

In [20]:
l1[[4]][2,2]

[1] 7

In [19]:
class(l1[[4]] )

[1] "matrix" "array"

In [21]:
str(l1)

List of 5
 $ num  : num [1:3] 1 3 5
 $ letra: chr [1:26] "A" "B" "C" "D" ...
 $ pl   : chr "Hoy es lunes"
 $ mat  : num [1:2, 1:2] 1 3 5 7
 $ lista:List of 2
  ..$ x  : chr [1:2] "a" "b"
  ..$ lgl: logi [1:3] TRUE FALSE FALSE


In [28]:
# de la lista l1[[5]], quiero el vector que está en el slot llamado "lgl" (segundo elemento)
l1[[5]][2] # Esto es una lista con el segundo elemento de la lista l1[[5]]


$lgl
[1]  TRUE FALSE FALSE

In [29]:
l1[[5]][[2]] # Esto es el vector que està en la segunda posicicòn dela lista l1[[5]]

[1]  TRUE FALSE FALSE

In [31]:
# Acceso mediante nombre
l1["letra"]# Mismo que antes: Lista con el elemtno "letra".



$letra
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [32]:
l1[["letra"]]# El vector que està en la segundaposiciòn de l1.

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [35]:
l1[["lista"]][["lgl"]]# Esto es el vector que està en la segunda posicicòn dela lista l1[[5]]

[1]  TRUE FALSE FALSE

In [36]:
# acceso vía "$"

l1$letra # es lo mismo que l1[[2]] o l1[["letra"]]



[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [37]:
l1$lista$lgl # Equivalente a l1[["lista"]][["lgl"]] o l1[[5]][[2]]

[1]  TRUE FALSE FALSE

In [39]:
# para saber el largo de la lista/vector
length(l1)
# Para obtener los nombres de la lista
names(l1)
# si quisiéramos renombrar los slots: TAREA, renombrar el quinto slot.


[1] 5

[1] "num"   "letra" "pl"    "mat"   "lista"

In [47]:
# También podemos crear nuevos "slots"
## Indicando nombre en [[]] y luego asignando
l1[["persona"]] <- c(nm="miguel", ap="Jorquera", ed="34")

In [48]:
l1$persona2 <- c(nm = "Sidney", ap = "Villalón", ed = "31")

In [46]:
str(l1)

List of 7
 $ num     : num [1:3] 1 3 5
 $ letra   : chr [1:26] "A" "B" "C" "D" ...
 $ pl      : chr "Hoy es lunes"
 $ mat     : num [1:2, 1:2] 1 3 5 7
 $ lista   :List of 2
  ..$ x  : chr [1:2] "a" "b"
  ..$ lgl: logi [1:3] TRUE FALSE FALSE
 $ persona : Named chr [1:3] "miguel" "Jorquera" "34"
  ..- attr(*, "names")= chr [1:3] "nm" "ap" "ed"
 $ persona2: Named chr [1:3] "Sidney" "Villalón" "31"
  ..- attr(*, "names")= chr [1:3] "nm" "ap" "ed"


In [50]:
# podemos modificar elementos dentro de un slot
# Quiero cambiar el "34" por un "35" , en el elemento 3 ("ed") del vector "persona"

l1$persona["ed"] <- 35




In [51]:
l1$persona

nm         ap         ed 
  "miguel" "Jorquera"       "35"

### 5.2 Dataframes

Un dataframe es un caso particular de una lista, donde los objetos de cada entrada corresponden a vectores de datos del mismo largo. E este caso cada vector corresponde a una columna del data.frame, mientras que la cantidad de filas corresponde al largo común de los vectores de cada entrada. El objeto resultante es una *tabla*, de ahora en adelante *data.frame*, cuyas columnas poseen distintos tipos de datos entre sí.

 * ¿Cómo se declara un dataframe?<br>
     Mediante la función data.frame(), indicando los vectores que conformarán las columnas.

 * ¿Cómo se accede a los datos de un data.frame?<br>
    Al ser una lista, se puede acceder de la misma manera. Sin embargo también es posible acceder del modo en que se accede a los elementos de una matriz.

In [52]:
# 5.2 Dataframes ----------
# Ejemplo sencillo de definición de un data.frame
# recordar que 1:3 es lo mismo que c(1,2,3)
df <- data.frame( nombre = c("Miguel", "Sidney", "Javiera"),
                  apellido = c("Jorquera", "Villalón", "Cuevas"),
                  edad = c(34,31,23))



In [53]:
str(df)

'data.frame':	3 obs. of  3 variables:
 $ nombre  : chr  "Miguel" "Sidney" "Javiera"
 $ apellido: chr  "Jorquera" "Villalón" "Cuevas"
 $ edad    : num  34 31 23


In [54]:
df

nombre  apellido edad
1 Miguel  Jorquera 34  
2 Sidney  Villalón 31  
3 Javiera Cuevas   23

In [59]:
# Acceso a columnas de un data.frame
## Igual que en una lista
# Colmuna 2
df[2] # Es un data.frame (antes era una lista) con el vector de apellidos


apellido
1 Jorquera
2 Villalón
3 Cuevas

In [60]:
df[[2]] # El vector de apellidos
df$apellido

[1] "Jorquera" "Villalón" "Cuevas"

[1] "Jorquera" "Villalón" "Cuevas"

In [58]:
## Igual que en una lmatriz
# Colmuna 2
df[,2]
df[,"apellido"]

[1] "Jorquera" "Villalón" "Cuevas"

[1] "Jorquera" "Villalón" "Cuevas"

In [61]:
##  Ganamos acceso como matriz
# segunda fila de df
df[2,]






nombre apellido edad
2 Sidney Villalón 31

In [63]:
# segunda columna y segunda fila
df[2,2]
df[2,"apellido"]

[1] "Villalón"

[1] "Villalón"

In [64]:
#Podemos crear nuevas columnas , del mismmo modo que creamos "slots" en una lista
df$tiene_mascota <- c(F,T,T)

In [65]:
df

nombre  apellido edad tiene_mascota
1 Miguel  Jorquera 34   FALSE        
2 Sidney  Villalón 31    TRUE        
3 Javiera Cuevas   23    TRUE

In [68]:
# podemos seleccionar más de una columna a la vez. Ej: seleccionar col 1 y col 4
df[c(1,4)] # Pensando en modo lista
df[,c(1,4)] # Pensando en modo matriz
# Referenciando el nombre de las columnas
df[c("nombre","tiene_mascota")] # Pensando en modo lista
df[,c("nombre","tiene_mascota")] # Pensando en modo matriz


nombre  tiene_mascota
1 Miguel  FALSE        
2 Sidney   TRUE        
3 Javiera  TRUE

nombre  tiene_mascota
1 Miguel  FALSE        
2 Sidney   TRUE        
3 Javiera  TRUE

nombre  tiene_mascota
1 Miguel  FALSE        
2 Sidney   TRUE        
3 Javiera  TRUE

nombre  tiene_mascota
1 Miguel  FALSE        
2 Sidney   TRUE        
3 Javiera  TRUE

In [69]:
df # Quiero los registros cuya edad sea mayora 30

nombre  apellido edad tiene_mascota
1 Miguel  Jorquera 34   FALSE        
2 Sidney  Villalón 31    TRUE        
3 Javiera Cuevas   23    TRUE

In [70]:
# edades:
df$edad

[1] 34 31 23

In [71]:
df[ df$edad > 30,]# Todas las columans, pero cuyas filas cumplamn con edad  >30

nombre apellido edad tiene_mascota
1 Miguel Jorquera 34   FALSE        
2 Sidney Villalón 31    TRUE

In [72]:
df[ df$edad > 30, "apellido"]

[1] "Jorquera" "Villalón"

In [74]:
# Quiero los mayores a 30 con mascota

df[ (df$edad > 30) & (df$tiene_mascota == TRUE),  ] # Todas las columnas, pero con un criterio por filas

nombre apellido
2 Sidney Villalón